{% set python_min = "3.10" %}

{% set name = "uv-secure" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uv_secure-{{ version }}.tar.gz
  sha256: b66fe6adacbd6a359fd72550bf5438ee46c11c55aeb108ff1b482e705a57b3ff

build:
  noarch: python
  entry_points:
    - uv-secure = uv_secure.run:app
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.7.2,<0.8.0
    - pip
  run:
    - stamina >=25.1.0
    - python >={{ python_min }}
    - anyio >=4.7.0
    - asyncer >=0.0.8
    - hishel >=1.1.2
    - httpx >=0.28.1
    - humanize >=4.11.0
    - inflect >=7.4.0
    - packaging >=25.0
    - pydantic >=2.10.3
    - rich >=13.9.4
    - tomli  # Can remove once min Python version reaches 3.11
    - typer >=0.15.1

test:
  imports:
    - uv_secure
  commands:
    - pip check
    - uv-secure --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Scan your uv.lock file for dependencies with known vulnerabilities
  home: https://github.com/owenlamont/uv-secure
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - owenlamont
